Change deeplink tip url
aeternity/superhero-ui pull request #1079
Opened 2021-05-12 07:30 UTC by etharner

After new wallet release `/tip` path will change to `/tips` and this deeplinks will break.

2021-05-12 07:37 UTC, AtanasKrondev approved these changes

2021-05-18 06:26 UTC, davidyuk requested changes
It makes less obvious that this deeplink does, proposing to make an internal redirect inside wallet instead

2021-06-16 09:59 UTC, thepiwo commented
@kenodressel @etharner @davidyuk whats the state of this?

2021-06-16 12:38 UTC, AtanasKrondev commented
Currently the deeplinks in production are broken and I suggest merging ASAP

2021-06-16 14:27 UTC, kenodressel commented
> It makes less obvious that this deeplink does, proposing to make an internal redirect inside wallet instead

too late now. lets merge this

2021-06-16 14:27 UTC, kenodressel approved these changes

2021-06-16 14:39 UTC, thepiwo approved these changes

2021-06-17 12:56 UTC, AtanasKrondev commented
Fixed in 28f9887ae2db1b968a6b054f0bfa3617469e7100

2021-06-17 12:56 UTC, closed without merging