Feature/inline comments loading
aeternity/superhero-ui pull request #796
Opened 2020-09-08 13:23 UTC by AtanasKrondev

Fixes #790 

When writing a comment after clicking send loading appears and also the textarea and the submit button are disabled while loading.

Fixes #772 

When on the tip details view clicking on the tip preview leads to the tipped url.

2020-09-08 14:56 UTC, mradkov commented
Can you resolve build errors. I think they are lint related.

2020-09-09 04:36 UTC, CedrikNikita requested changes
I propose to have the loading component "inside" the texarea, like the button "arrow". For me it looks more consistent and doesn't create unnecessary proprs.
![Loading animation](https://user-images.githubusercontent.com/9008074/92554882-bba88600-f2a9-11ea-88c5-1aa3a8212c51.gif)

2020-09-10 05:53 UTC, mradkov commented
Can you resolve the conflicts?

2020-09-11 01:08 UTC, CedrikNikita commented
Do not merge develop into your branch, use rebase instead.

2020-09-14 11:14 UTC, mradkov approved these changes

2020-09-14 11:14 UTC, merged